### ISSUE TITLE
API documentation js.html lost

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/html-externs#4]
I found this older documentation here:
https://github.com/HaxeFoundation/haxe/blob/a06f9d35ae138be1e163444146354933301697f4/std/js/html/CSSRule.hx

The current looks like this:
https://github.com/HaxeFoundation/haxe/blob/development/std/js/html/CSSRule.hx

Which result in:
http://api.haxe.org/js/html/CSSRule.html

As far as I see, there is no documentation in the full package anymore. Can we get this back?

**Comment by aduros** [comment]
Yeah, it didn't make it for 3.2. Some of the generated docs were badly formatted, or just plain wrong.

Maintaining docs by hand would be way too much work. I wonder if there's a machine readable doc source out there that we can use.

**Comment by markknol** [comment]
I contacted a MDN contributor, he told me this

> So, IDLs differ from browser to browser and there are usually no docs in them.
> MDN is quite structured, but it is a wiki so not perfectly structured.
> We are making progress to be more and more structured, so that tools and consume our content.
> So, maybe you can't embed all the information from MDN today, but you can certainly link to many of them.
> The URL is always the same: https://developer.mozilla.org/en-US/docs/Web/API/<interface>
>
> For embedding, there are URLs like this https://developer.mozilla.org/en-US/docs/Web/API/AbstractWorker?raw&macros&section=Example
> where "Example" is a headline in the article.
> https://developer.mozilla.org/en-US/docs/Web/API/AbstractWorker
>
> See https://developer.mozilla.org/en-US/docs/MDN/Contribute/Tools/Document_parameters for more info

Is this something we can use ? It would be nice if we can scrape the content out of this and use it as documentation.
